### ISSUE TITLE
Sent wrong amount BCH to your donating address

### ISSUE THREAD

**Issue by corper** [simpleledger/simple-ledger-protocol#1]
Hi,
I want to send 100 USD BCH to your donating address at first. But I sent 18.14 BCH by mistake. Can you send back 18 BCH to one of the inputs address? The transaction is https://bch.btc.com/2435165ffc5e606283349c866d4629fd958fad0991ed12fec3c0545b9ac3ad0e
This is my mistake. I'm sorry to bother you.
Thank you.

BTW. SLP is a creative idea. And I will introduce it to Chinese BCH community.

**Comment by jcramer** [comment]
Hi Edward, 

Please confirm for me that you have received back you funds.
[https://bch.btc.com/qzdzlkh5jgazaa60r8lukn0yqeayv6erwvtc5yjrg9](https://bch.btc.com/qzdzlkh5jgazaa60r8lukn0yqeayv6erwvtc5yjrg9)

I appreciate your very generous 0.14 donation, l will make sure it gets put to good use towards project expenses.  If you have any suggestions in the draft specification you can let me know.  Still lots of work to do yet, but each day the applications seem to be broadening as we think of good use cases.  

Thanks!

**Comment by jcramer** [comment]
Also do you want to donate $100 or 0.14 BCH?  I can return more if you want to stick with $100 even.

________________________________

**Comment by corper** [comment]
Hi,

I've received the BCH. 18 is enough, and thank you very much.
I'm trying to understand the protocol and will ask some questions in another thread.

Thanks.

**Comment by jcramer** [comment]
Great, thanks!
