### ISSUE TITLE
Why we need the sig parameter in moniker ledger?

### ISSUE THREAD

**Issue by corper** [simpleledger/simple-ledger-protocol#2]
Hi,
There is description about the moniker ledger:

> In this SLP mode monikers or names can be associated with a particular bitcoin cash address. A valid signature by the moniker's owner will be required in a signature field (i.e. sig=), and the most recently signed moniker with a particular address would be used by an implementation.

Can we just associate the moniker without sig parameter?

Thanks.

**Comment by jcramer** [comment]
Yes, the sig parameter can be optional and probably is not needed any most scenarios.  It was just a way to verify that the owner of the address consented to the respective moniker.

I will spend some time next week cleaning up the description

**Comment by jcramer** [comment]
I made a quick edit to reflect optional sig=, I'll re-read on Monday to see if I can improve.

**Comment by jcramer** [comment]
FYI I added a couple more modes up front to aid in discussing the different applications.  The `label` and `lookup` modes have some pretty interesting applications.  If you have time please let me know what you think.

I'm going to close this issue, for now, I think I've resolved it.
